# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Copy project files
COPY pyproject.toml README.md ./
COPY src ./src

# Install build tool hatchling
RUN pip install --no-cache-dir hatchling

# Install the package and its dependencies
RUN pip install --no-cache-dir .

# Default command
CMD ["bitable-mcp"]
